### ISSUE TITLE
Latest 2 sessions overlap in the ui

### ISSUE THREAD

**Issue by ezonius** [OvenProofMars/Power_DI#15]
![image](https://github.com/OvenProofMars/Power_DI/assets/61872098/daf20519-7db5-4d1b-a20e-d8ba1430a982)

The latest 2 sessions overlaps in the UI, and clicking on them accesses not the latest, but the second most latest.

Not sure what could have caused it, just start happening recently, or at least I noticed it recently.

**Comment by ezonius** [comment]
Opening the sessions screen seems not scroll to the top, I think it normally scrolls to the top, but not sure. The thing is that there is an entry missing at that point so maybe that's related?

![image](https://github.com/OvenProofMars/Power_DI/assets/61872098/d27df737-f4f4-458d-9a8f-68b48aa1a045)

**Comment by OvenProofMars** [comment]
I've had this happen once as well, and I can't explain it. I think it may be an issue with Fat Shark's grid code, as I'm pretty sure I've seen this happen in the social screen as well. Deleting the session that overlaps solved it for me, and I've not had it happen since. The scrolling issue is probably related, as I think that it is trying to scroll to the position where the item should be.

**Comment by ezonius** [comment]
Thanks, deleting the session solved the issue 👍
